package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"

	"github.com/genghisjahn/pokerbrain/poker"
)

func main() {
	log.Println("Started")
	http.HandleFunc("hand/score", handscoreHandler)
	http.HandleFunc("table/score", tableScoreHandler)
	log.Fatal(http.ListenAndServe("localhost:8080", nil))
}

func tableScoreHandler(w http.ResponseWriter, r *http.Request) {
	method := r.Method
	if method != "POST" {
		http.Error(w, fmt.Sprintf("%s not allowed", method), http.StatusMethodNotAllowed)
		return
	}
	poker.BuildDeck()
	decoder := json.NewDecoder(r.Body)
	var p []poker.Player
	err := decoder.Decode(&p)
	if err != nil {
		panic(err)
	}
	log.Println(p)
}

func handscoreHandler(w http.ResponseWriter, r *http.Request) {
	method := r.Method
	if method != "GET" {
		http.Error(w, fmt.Sprintf("%s not allowed", method), http.StatusMethodNotAllowed)
		return
	}
	poker.BuildDeck()
	hand := poker.Hand{}
	vals := strings.Split(r.FormValue("h"), "|")
	for k, v := range vals[:5] {
		hand.Cards[k] = poker.DeckCardMap[v]
	}
	hand.SetScore()
	jdata, _ := json.Marshal(hand)
	w.Header().Set("Content-Type", "application/json")
	w.Write(jdata)
}

/* Players hands json

[
   {
      "Name":"Bill",
      "Cards":[
         {
            "suit":"♧",
            "Name":"3"
         },
         {
            "suit":"♧",
            "Name":"6"
         },
         {
            "suit":"♧",
            "Name":"7"
         },
         {
            "suit":"♧",
            "Name":"8"
         },
         {
            "suit":"♧",
            "Name":"A"
         }
      ],
      "Score":"000000010000000001408070603",
      "Position":2,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♧",
            "Name":"7"
         },
         {
            "suit":"♧",
            "Name":"3"
         }
      ]
   },
   {
      "Name":"Frank",
      "Cards":[
         {
            "suit":"♧",
            "Name":"6"
         },
         {
            "suit":"♤",
            "Name":"6"
         },
         {
            "suit":"♢",
            "Name":"10"
         },
         {
            "suit":"♧",
            "Name":"A"
         },
         {
            "suit":"♤",
            "Name":"A"
         }
      ],
      "Score":"000000000001406001414100606",
      "Position":6,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♤",
            "Name":"A"
         },
         {
            "suit":"♤",
            "Name":"6"
         }
      ]
   },
   {
      "Name":"David",
      "Cards":[
         {
            "suit":"♤",
            "Name":"7"
         },
         {
            "suit":"♢",
            "Name":"7"
         },
         {
            "suit":"♢",
            "Name":"10"
         },
         {
            "suit":"♡",
            "Name":"10"
         },
         {
            "suit":"♧",
            "Name":"A"
         }
      ],
      "Score":"000000000001007001410100707",
      "Position":4,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♢",
            "Name":"7"
         },
         {
            "suit":"♡",
            "Name":"10"
         }
      ]
   },
   {
      "Name":"Edward",
      "Cards":[
         {
            "suit":"♤",
            "Name":"7"
         },
         {
            "suit":"♡",
            "Name":"7"
         },
         {
            "suit":"♧",
            "Name":"8"
         },
         {
            "suit":"♤",
            "Name":"8"
         },
         {
            "suit":"♧",
            "Name":"A"
         }
      ],
      "Score":"000000000000807001408080707",
      "Position":5,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♤",
            "Name":"8"
         },
         {
            "suit":"♡",
            "Name":"7"
         }
      ]
   },
   {
      "Name":"Jon",
      "Cards":[
         {
            "suit":"♤",
            "Name":"7"
         },
         {
            "suit":"♧",
            "Name":"8"
         },
         {
            "suit":"♢",
            "Name":"10"
         },
         {
            "suit":"♧",
            "Name":"A"
         },
         {
            "suit":"♡",
            "Name":"A"
         }
      ],
      "Score":"000000000000000141414100807",
      "Position":10,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♡",
            "Name":"A"
         },
         {
            "suit":"♤",
            "Name":"4"
         }
      ]
   },
   {
      "Name":"Ivan",
      "Cards":[
         {
            "suit":"♤",
            "Name":"7"
         },
         {
            "suit":"♧",
            "Name":"8"
         },
         {
            "suit":"♢",
            "Name":"10"
         },
         {
            "suit":"♤",
            "Name":"10"
         },
         {
            "suit":"♧",
            "Name":"A"
         }
      ],
      "Score":"000000000000000101410100807",
      "Position":9,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♢",
            "Name":"3"
         },
         {
            "suit":"♤",
            "Name":"10"
         }
      ]
   },
   {
      "Name":"Greg",
      "Cards":[
         {
            "suit":"♧",
            "Name":"8"
         },
         {
            "suit":"♡",
            "Name":"8"
         },
         {
            "suit":"♢",
            "Name":"10"
         },
         {
            "suit":"♤",
            "Name":"J"
         },
         {
            "suit":"♧",
            "Name":"A"
         }
      ],
      "Score":"000000000000000081411100808",
      "Position":7,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♡",
            "Name":"8"
         },
         {
            "suit":"♤",
            "Name":"J"
         }
      ]
   },
   {
      "Name":"Charles",
      "Cards":[
         {
            "suit":"♧",
            "Name":"8"
         },
         {
            "suit":"♢",
            "Name":"10"
         },
         {
            "suit":"♤",
            "Name":"Q"
         },
         {
            "suit":"♢",
            "Name":"K"
         },
         {
            "suit":"♧",
            "Name":"A"
         }
      ],
      "Score":"000000000000000001413121008",
      "Position":3,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♤",
            "Name":"Q"
         },
         {
            "suit":"♢",
            "Name":"K"
         }
      ]
   },
   {
      "Name":"Henry",
      "Cards":[
         {
            "suit":"♤",
            "Name":"7"
         },
         {
            "suit":"♧",
            "Name":"8"
         },
         {
            "suit":"♢",
            "Name":"10"
         },
         {
            "suit":"♧",
            "Name":"K"
         },
         {
            "suit":"♧",
            "Name":"A"
         }
      ],
      "Score":"000000000000000001413100807",
      "Position":8,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♢",
            "Name":"5"
         },
         {
            "suit":"♧",
            "Name":"K"
         }
      ]
   },
   {
      "Name":"Adam",
      "Cards":[
         {
            "suit":"♤",
            "Name":"7"
         },
         {
            "suit":"♧",
            "Name":"8"
         },
         {
            "suit":"♢",
            "Name":"10"
         },
         {
            "suit":"♢",
            "Name":"J"
         },
         {
            "suit":"♧",
            "Name":"A"
         }
      ],
      "Score":"000000000000000001411100807",
      "Position":1,
      "Stake":100,
      "Pocket":[
         {
            "suit":"♢",
            "Name":"J"
         },
         {
            "suit":"♢",
            "Name":"2"
         }
      ]
   }
]

*/
